// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemaProducao3D.Data.Context;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260305171056_AddEventosImpressora")]
    partial class AddEventosImpressora
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SistemaProducao3D.Modelos.Modelos.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("Densidade")
                        .HasPrecision(5, 3)
                        .HasColumnType("numeric(5,3)")
                        .HasColumnName("densidade");

                    b.Property<string>("Fabricante")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fabricante");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<Guid>("UltimakerMaterialGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("ultimaker_material_guid");

                    b.HasKey("Id");

                    b.HasIndex("UltimakerMaterialGuid")
                        .IsUnique();

                    b.ToTable("materiais", (string)null);
                });

            modelBuilder.Entity("SistemaProducao3D.Modelos.Modelos.MesaProducao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatetimeFinished")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datetime_finished");

                    b.Property<DateTime>("DatetimeStarted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datetime_started");

                    b.Property<bool>("IsPrototype")
                        .HasColumnType("boolean")
                        .HasColumnName("is_prototype");

                    b.Property<bool>("IsRecondicionado")
                        .HasColumnType("boolean")
                        .HasColumnName("is_recondicionado");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("job_id");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("job_name");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("job_type");

                    b.Property<int>("MachineId")
                        .HasColumnType("integer")
                        .HasColumnName("machine_id");

                    b.Property<decimal>("Material0Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("material_0_amount");

                    b.Property<Guid?>("Material0Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("material_0_guid");

                    b.Property<decimal>("Material0WeightG")
                        .HasColumnType("numeric")
                        .HasColumnName("material_0_weight_g");

                    b.Property<decimal>("Material1Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("material_1_amount");

                    b.Property<Guid?>("Material1Guid")
                        .HasColumnType("uuid")
                        .HasColumnName("material_1_guid");

                    b.Property<decimal>("Material1WeightG")
                        .HasColumnType("numeric")
                        .HasColumnName("material_1_weight_g");

                    b.Property<int>("MesaId")
                        .HasColumnType("integer")
                        .HasColumnName("mesa_id");

                    b.Property<decimal>("PrintTime")
                        .HasColumnType("numeric")
                        .HasColumnName("print_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("UltimakerJobUuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ultimaker_job_uuid");

                    b.HasKey("Id");

                    b.ToTable("mesas_producao", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
